name: Sonar Scanner

on:
  push:
    branches: main

jobs:
  tasks:
    if: github.actor != 'readme-generate'
    uses: alves-dev/actions/.github/workflows/sonar.yml@v1
    with:
      repo-name: ${{ github.event.repository.name }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
